SERVER = testlab
USER = testlab

all:
	scp RBv1 $(SERVER)@$(USER):/var/testlab/compile/RBv1
	scp RBv2 $(SERVER)@$(USER):/var/testlab/compile/RBv2
	scp RBv3 $(SERVER)@$(USER):/var/testlab/compile/RBv3
