SERVER = testlab
USER = testlab

all:
	scp -rp connection $(SERVER)@$(USER):/var/testlab/conf/connection
	scp -rp sconnection $(SERVER)@$(USER):/var/testlab/conf/sconnection
	scp -rp mobile $(SERVER)@$(USER):/var/testlab/conf/mobile
	scp -rp sms $(SERVER)@$(USER):/var/testlab/conf/sms
	scp -rp upload_fw $(SERVER)@$(USER):/var/testlab/conf/upload_fw
