SERVER = testlab
USER = testlab

all:
	scp -rp connection $(SERVER)@$(USER):/var/testlab/tests/connection
	scp -rp sconnection $(SERVER)@$(USER):/var/testlab/tests/sconnection
	scp -rp mobile $(SERVER)@$(USER):/var/testlab/tests/mobile
	scp -rp sms $(SERVER)@$(USER):/var/testlab/tests/sms
	scp -rp upload_fw $(SERVER)@$(USER):/var/testlab/tests/upload_fw
