SERVER = testlab
USER = testlab

all:
	scp -rp connect $(SERVER)@$(USER):/var/testlab/tests/
	scp -rp connect_ssh $(SERVER)@$(USER):/var/testlab/tests/
	scp -rp firmware $(SERVER)@$(USER):/var/testlab/tests/
	scp -rp configuration $(SERVER)@$(USER):/var/testlab/tests/
	scp -rp mobile $(SERVER)@$(USER):/var/testlab/tests/
	scp -rp mobile_ppp $(SERVER)@$(USER):/var/testlab/tests/
	scp -rp mobile_usb $(SERVER)@$(USER):/var/testlab/tests/
	scp -rp mobile_edge $(SERVER)@$(USER):/var/testlab/tests/
	scp -rp mobile_umts $(SERVER)@$(USER):/var/testlab/tests/
	scp -rp mobile_lte $(SERVER)@$(USER):/var/testlab/tests/
	scp -rp mobile_sim2 $(SERVER)@$(USER):/var/testlab/tests/
