SERVER = testlab
USER = testlab

all:
	scp -rp connection $(SERVER)@$(USER):/var/testlab/tests/
	scp -rp sconnection $(SERVER)@$(USER):/var/testlab/tests/
	scp -rp mobile $(SERVER)@$(USER):/var/testlab/tests/
	scp -rp sms $(SERVER)@$(USER):/var/testlab/tests/
	scp -rp upload_fw $(SERVER)@$(USER):/var/testlab/tests/
