all:
	pdflatex felgr_david.tex
	pdflatex felgr_david.tex
	evince felgr_david.pdf

purge:
	-rm *.log
	-rm *.aux
	-rm *.toc
	-rm *.bbl
	-rm *.blg
	-rm *.bcf
	-rm *.idx
	-rm *.ilg
	-rm *.ind
	-rm *.out
	-rm *.run.xml

clean: purge
	-rm -f felgr_david.pdf


