SERVER = testlab
USER = testlab

all:
	scp RBv1 $(SERVER)@$(USER):/var/testlab/checkout/RBv1
	scp RBv2 $(SERVER)@$(USER):/var/testlab/checkout/RBv2
	scp RBv3 $(SERVER)@$(USER):/var/testlab/checkout/RBv3
