SERVER = testlab
USER = testlab

all:
	scp -r images $(SERVER)@$(USER):/var/www/html/
	scp -r inc $(SERVER)@$(USER):/var/www/html/
	scp index.php $(SERVER)@$(USER):/var/www/html/
	scp style.css $(SERVER)@$(USER):/var/www/html/
